kind: Service
apiVersion: v1
metadata:
  name: api
  namespace: test
spec:
  selector:
    app: myapp
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer